добавление фильтра по году и жанру в метод топ-фильмов
mifisto75/java-filmorate pull request #45
Opened 2023-07-08 11:55 UTC by garistip

2023-07-08 13:28 UTC, julia-gerasimenko requested changes
Отличная работа, добавить нечего, у меня пара замечаний к CodeStyle

2023-07-08 13:28 UTC, julia-gerasimenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            ;
лишняя ;

2023-07-08 13:28 UTC, julia-gerasimenko commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> popularFilm(Integer count, Integer genreId, Integer year) {
названия методов принято начинать с глаголов, типа getPopularfilms

2023-07-08 14:30 UTC, CheTigor reviewed
Понравился метод popularFilm - только название бы поменять на getPopularFilms.
Пара вопросов есть, посмотри

2023-07-08 14:30 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count < 1) {
Можно, например в контроллере, перед count поставить аннотацию @Positive - тогда такая проверка не нужна, но если требуется вывести именно ValidationException, тогда можно оставить

2023-07-08 14:30 UTC, CheTigor commented on src/main/java/ru/yandex/practicum/filmorate/storage/Dao/LikeDao.java
> -    List<Integer> sizeLikeFilmList(int count);
Зачем удалил count? Из за этого теряется смысл метода

2023-07-08 15:31 UTC, garistip commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +            ;
Спасибо удалю

2023-07-08 15:32 UTC, garistip commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public List<Film> popularFilm(Integer count, Integer genreId, Integer year) {
Исправлю

2023-07-08 15:32 UTC, garistip commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (count < 1) {
попробую @positive

2023-07-08 15:35 UTC, garistip commented on src/main/java/ru/yandex/practicum/filmorate/storage/Dao/LikeDao.java
> -    List<Integer> sizeLikeFilmList(int count);
sizeLikeFilmList используется только в getPopularFilm поэтому решил его модифицировать т.к. по другому не знаю как реализовать логику.
sizeLikeFilmList смысл метода остается, он выводит популярные фильмы и сортирует их по популярности, но только без лимита count по размеру списка
ограничение count я уже добавил в самом конце метода getPopularFilm

2023-07-08 16:04 UTC, julia-gerasimenko approved these changes

2023-07-10 19:01 UTC, marina52746 approved these changes
Мне все понравилось)

2023-07-10 21:33 UTC, merged